[package]
name = "layout"
version = "0.1.0"
edition = "2021"
authors = ["DesignCompose Team <aae-design-compose@google.com>"]
description = "Figma node layout library for Android"
license = "Apache-2.0"
rust-version = "1.68"

[lib]
crate-type = ["rlib", "cdylib"]

[features]
fetch_layout = ["clap"]

[dependencies]
figma_import = {path="../figma_import"}
log = "0.4"
android_logger = "0.13.1"
serde = { version = "1.0", features = ["derive", "rc"] }
serde_json = "1.0"
serde_bytes = "0.11"
bincode = "1.3"
taffy = "0.3.18"
lazy_static = "1.4.0"
clap = { version = "4.5", features = ["derive"], optional = true }

[[bin]]
name = "fetch_layout"
path = "src/bin/fetch_layout.rs"
required-features = ["fetch_layout"]
