name: Lints

on:
  label:
    types:
      - created
  push:
    branches:
      - main
      - 'stable/**'
  merge_group:
  pull_request:

jobs:
  super-lint:
    name: SuperLinter
    runs-on: ubuntu-latest

    # Grant status permission for MULTI_STATUS #
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
